import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";

const kanit = Kanit({ weight: ["400", "500", "600", "800"], subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Barber Voyage | Find Your Best Barber",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.className} bg-bgCol`}>{children}</body>
    </html>
  );
}
