import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/providers/ReduxProvider";
import { Toaster } from "react-hot-toast";
import AuthProvider from "@/providers/AuthProvider";

const kanit = Kanit({ weight: ["400", "500", "600", "800"], subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Barber Voyage | Find Your Best Barber",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <ReduxProvider>
          <AuthProvider>
            <body className={`${kanit.className} bg-bgCol`}>
              <Toaster />
              {children}
            </body>
          </AuthProvider>
        </ReduxProvider>
      </html>
    </>
  );
}
